use_frameworks!

platform :ios, '9.0'

target 'WQCameraController_Example' do
#  pod 'WQCameraController', :path => '../'
  pod 'WQCameraController'

  target 'WQCameraController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
